//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class JobSeeker
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<bool> GENDER { get; set; }
        public string Address { get; set; }
        public string Mobile { get; set; }
        [Display(Name="Picture")]
        public string resume { get; set; }
        public string Skills { get; set; }
        public Nullable<int> Country { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<bool> IsJava { get; set; }
        public Nullable<bool> IsDotnet { get; set; }
        public Nullable<bool> IsSAP { get; set; }
    
        public virtual Country Country1 { get; set; }
    }
}
